/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColonyBoard: typeof import('./components/ColonyBoard.vue')['default']
    ConnectionBadge: typeof import('./components/ConnectionBadge.vue')['default']
    MoonBackdrop: typeof import('./components/backdrops/MoonBackdrop.vue')['default']
    PlayerChips: typeof import('./components/PlayerChips.vue')['default']
    ProfileEditor: typeof import('./components/ProfileEditor.vue')['default']
    RankSheet: typeof import('./components/RankSheet.vue')['default']
    RobotAvatar: typeof import('./components/RobotAvatar.vue')['default']
    RoomQrSheet: typeof import('./components/RoomQrSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TokenCounter: typeof import('./components/TokenCounter.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
  }
}
